### ISSUE TITLE
Received value [] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]

### ISSUE THREAD

**Issue by teriyakichild** [rackerlabs/zabbix_url_monitor#16]
The url_monitor command to run all checks doesn't return anything to stdout.  This causes the "Run all checks" item to go unsupported.  

```
# url_monitor check  2>/dev/null
# 
```

**Comment by teriyakichild** [comment]
#19 closes this

**Comment by wenxn** [comment]
do you erver use python ?print and echo can exchange???
