### ISSUE TITLE
When passing --loglevel debug, the cleartext password is written to stderr and the log file

### ISSUE THREAD

**Issue by teriyakichild** [rackerlabs/zabbix_url_monitor#17]
When passing "--loglevel debug", the cleartext password is written to stderr and the log file.  I would imagine that when using syslog, the password would also be logged there.

**Comment by jonkelleyatrackspace** [comment]
Fixed https://github.com/rackerlabs/zabbix_url_monitor/pull/23/commits/99eeece985931645230d592055f4f1ca57b3222b
